### ISSUE TITLE
Katharsis should honor @JsonToXX and not look at the field and getter

### ISSUE THREAD

**Issue by chb0github** [katharsis-project/katharsis-framework#66] opened 2016-08-10 23:59 UTC
I am using futures and then delegating my getters to return the result of the future. 

by annotating with `@JsonApiToXX` (any of the relationship annotations) my getter methods I am clearly indicating to Katharsis how it should determine relationships and what types to use.

However, Katharsis decides to look at both the field and the getter of the same name and chooses the field as the entity to relate to when it has both. In this scenario, Katharsis should only look where the annotation is.

The work around is to have a field name containing the future slightly differently named than the getter. This literally doubles the code.

```java
public class Example {
    
   // When Katharis sees this situation it decides to use the CompletableFuture field as the entity!
    private CompleteableFuture<Person> person;
    
    @JsonApiToOne
    public Person getPerson() {
        return person.get();
    }

}
```
This is really inconvenient as it forces me to do a lot of code gymnastics to move between the future and the value. Especially when you start using DI with spring

**Comment by meshuga** [comment] 2016-08-11 06:35
Duplicate of https://github.com/katharsis-project/katharsis-framework/issues/21

**Closed by meshuga** 2016-08-11 06:35 UTC
Labels: enhancement, katharsis-core

**Comment by chb0github** [comment] 2016-08-11 21:32
Sorry about that. I couldn't find the original. Wasn't sure if it got lost in the move
